"""Example: figure panels with multiple layouts.

This script demonstrates arranging several figures in a row, a column, and a
3×2 grid. It also shows per-figure sizing and an optional panel caption.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from bioinformatics_report import Report

OUT = Path(__file__).with_suffix("").parent / "out" / "figure_panel_demo"
ASSETS = OUT / "assets"
ASSETS.mkdir(parents=True, exist_ok=True)


# ── Generate six simple placeholder figures ───────────────────────────────
def make_bar(path: Path, title: str, color: str) -> None:
    fig, ax = plt.subplots(figsize=(3, 2.5))
    labels = ["A", "B", "C"]
    values = np.random.randint(10, 100, size=3)
    ax.bar(labels, values, color=color)
    ax.set_title(title, fontsize=10)
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)


colors = ["#264882", "#637A9F", "#9FADC4", "#D38726", "#e8edf4", "#1a2a4a"]
fig_paths = []
for i in range(1, 7):
    path = ASSETS / f"panel_{i}.png"
    make_bar(path, f"Panel {i}", colors[i - 1])
    fig_paths.append(path)

# ── Build report ─────────────────────────────────────────────────────────
report = Report(
    title_line1="Figure Panel",
    title_line2="Layout Demo",
    date="2026-06-29",
    run_label="Demo",
    run_status="Demo ready",
    sidebar_footer="Demo ready",
    footer_left="Figure Panel Demo",
    footer_right="Generated by bioinformatics-report",
)

# Three figures side by side in a single row.
row_section = report.add_section("01", "Row Layout", count="3 figures")
row_section.add_figure_panel(
    fig_paths[:3],
    captions=["First panel", "Second panel", "Third panel"],
    layout="row",
)

# Three figures stacked vertically.
col_section = report.add_section("02", "Column Layout", count="3 figures")
col_section.add_figure_panel(
    fig_paths[:3],
    captions=["Top", "Middle", "Bottom"],
    layout="column",
)

# Six figures in a 3×2 grid.
grid_section = report.add_section("03", "Grid Layout", count="3×2 matrix")
grid_section.add_figure_panel(
    [
        {"path": fig_paths[0], "caption": "Top-left", "width": "95%"},
        {"path": fig_paths[1], "caption": "Top-middle", "width": "95%"},
        {"path": fig_paths[2], "caption": "Top-right", "width": "95%"},
        {"path": fig_paths[3], "caption": "Bottom-left", "width": "95%"},
        {"path": fig_paths[4], "caption": "Bottom-middle", "width": "95%"},
        {"path": fig_paths[5], "caption": "Bottom-right", "width": "95%"},
    ],
    layout=3,
    panel_caption=(
        "Six related metrics arranged in a 3×2 matrix. Each panel shows a different sample."
    ),
    panel_label="Fig. 7",
)

qmd = report.save(OUT, filename="figure_panel_demo.qmd")
print(f"Figure panel demo written to: {qmd}")
print("Render with: quarto render", qmd, "--to html")
