"""Example: gut virome / metagenomics classification report."""

from pathlib import Path

import matplotlib.pyplot as plt

from bioinformatics_report import Report

OUT = Path(__file__).with_suffix("").parent / "out" / "metagenomics"
ASSETS = OUT / "assets"
ASSETS.mkdir(parents=True, exist_ok=True)

# ── Generate a placeholder figure ────────────────────────────────────────
fig, ax = plt.subplots(figsize=(7, 3))
orders = ["Caudovirales", "Petitvirales", "Tubulavirales", "Hafunavirales", "Unclassified"]
values = [61.4, 14.2, 8.7, 3.0, 12.7]
colors = ["#264882", "#637A9F", "#9FADC4", "#D38726", "#e8edf4"]
ax.barh(orders, values, color=colors)
ax.set_xlabel("Relative abundance (%)")
ax.set_title("Taxonomic classification of phage contigs")
ax.invert_yaxis()
for spine in ["top", "right"]:
    ax.spines[spine].set_visible(False)
fig.tight_layout()
fig_path = ASSETS / "taxonomy.png"
fig.savefig(fig_path, dpi=150)
plt.close(fig)

# ── Build report ─────────────────────────────────────────────────────────
report = Report(
    title_line1="Phage Genomics",
    title_line2="Classification Report",
    pipeline="Jaeger v2.1.0 · Zeus HPC",
    operator="Y. Samarawickrama",
    reference="INPHARED 2025-01",
    cluster="Zeus HPC · L40S",
    date="2026-06-26",
    run_label="Jaeger v2.1.0 · Zeus HPC",
    run_status="Pipeline complete · 48/48 samples",
    sidebar_footer="Pipeline complete",
    # Swap the logo to any SVG, PNG or JPG; use set_logo() or omit for a placeholder.
    logo_path=Path(__file__).resolve().parent / "assets" / "Unimed_logo.svg",
    footer_left="Jaeger v2.1.0 · Zeus HPC · 2026-06-26",
    footer_right=(
        "Generated by the Kaderali Lab · Institute of Bioinformatics, "
        "Universitätsmedizin Greifswald"
    ),
)
report.set_metadata(
    [
        ("Date", "2026-06-26"),
        ("Samples", "n = 48"),
        ("Phage contigs", "14,382"),
        ("Classified", "87.3%"),
        ("Novel", "1,821"),
    ]
)

summary = report.add_section("01", "Executive Summary", count="48 samples · 14,382 contigs")
summary.set_overview(
    "All 48 gut virome samples processed successfully. Classification confidence exceeded "
    "threshold on 87.3% of assembled contigs. A subset of 1,821 sequences with <50% AAI to "
    "any known reference were flagged as putatively novel."
)
summary.add_metrics(
    [
        {
            "label": "Phage Contigs",
            "value": "14,382",
            "sub": "across 48 samples",
            "highlight": True,
        },
        {"label": "Mean Length", "value": "28.4 kb", "sub": "N50 = 41.2 kb"},
        {"label": "Classified", "value": "87.3%", "sub": "score > 0.5"},
        {"label": "Novel Phages", "value": "1,821", "sub": "<50% AAI to refs"},
        {"label": "Dominant Order", "value": "Caudovirales", "sub": "61.4% of contigs"},
    ]
)

qc = report.add_section("02", "Quality Control", count="fastp v0.23 · Bowtie2 · GRCh38")
qc.add_subsection("Preprocessing", "s2-preproc")
qc.add_notice(
    "Info",
    "Raw reads adapter-trimmed with Fastp (v0.23). Low-complexity sequences filtered.",
)
qc.add_subsection("Sample table", "s2-table")
qc.add_table(
    headers=["Sample ID", "Raw Reads", "After QC", "% Retained", "Host %", "Status"],
    rows=[
        ["SHIP_001", "22,481,334", "21,904,112", "97.4", "0.8", "✓ pass"],
        ["SHIP_002", "19,033,801", "18,512,405", "97.3", "1.1", "✓ pass"],
        ["SHIP_003", "16,240,012", "15,108,994", "93.0", "2.4", "~ warn"],
        ["SHIP_004", "24,770,556", "24,312,001", "98.1", "0.5", "✓ pass"],
        ["SHIP_005", "9,812,003", "7,488,230", "76.3", "8.2", "✗ fail"],
    ],
    caption="Table 1 · 5 of 48 samples shown",
    col_classes=["mono", "mono", "mono", "mono", "mono", None],
    cell_classes=[
        [None, None, None, None, None, "status pass"],
        [None, None, None, None, None, "status pass"],
        [None, None, None, None, None, "status warn"],
        [None, None, None, None, None, "status pass"],
        [None, None, None, None, None, "status fail"],
    ],
)

cls = report.add_section("03", "Classification", count="Jaeger v2.1.0 · threshold 0.5")
cls.add_subsection("Taxonomy breakdown", "s3-taxa")
cls.add_freq_bars(
    [
        ("Caudovirales", 61.4),
        ("Petitvirales", 14.2),
        ("Tubulavirales", 8.7),
        ("Hafunavirales", 3.0),
        ("Unclassified", 12.7),
    ]
)
cls.add_figure(fig_path, caption="Relative abundance of classified phage orders.")

refs = report.add_section("04", "References")
refs.add_references(
    [
        "Chen S. et al. (2018). fastp: an ultra-fast all-in-one FASTQ "
        "preprocessor. Bioinformatics, 34(17), i884–i890.",
        "Li D. et al. (2015). MEGAHIT: an ultra-fast single-node solution for "
        "large and complex metagenomics assembly. Bioinformatics, 31(10), "
        "1674–1676.",
        "Samarawickrama Y. et al. (2024). Jaeger: a CNN-based phage sequence classifier. bioRxiv.",
    ]
)

qmd = report.save(OUT, filename="metagenomics_report.qmd")
print(f"Metagenomics report written to: {qmd}")
print("Render with: quarto render", qmd, "--to html")
