"""Example: multi-omics integration report (transcriptomics + proteomics + metabolomics)."""

from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

from bioinformatics_report import Report

OUT = Path(__file__).with_suffix("").parent / "out" / "multi_omics"
ASSETS = OUT / "assets"
ASSETS.mkdir(parents=True, exist_ok=True)

# ── Generate placeholder correlation heatmap ─────────────────────────────
fig, ax = plt.subplots(figsize=(5, 4))
labels = ["mRNA", "Protein", "Metabolite", "Clinical"]
corr = np.array([
    [1.00, 0.72, 0.58, 0.41],
    [0.72, 1.00, 0.65, 0.38],
    [0.58, 0.65, 1.00, 0.55],
    [0.41, 0.38, 0.55, 1.00],
])
im = ax.imshow(corr, cmap="Blues", vmin=0, vmax=1)
ax.set_xticks(np.arange(len(labels)))
ax.set_yticks(np.arange(len(labels)))
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)
for i in range(len(labels)):
    for j in range(len(labels)):
        ax.text(j, i, f"{corr[i, j]:.2f}", ha="center", va="center", color="white" if corr[i, j] > 0.6 else "black")
ax.set_title("Multi-omics correlation matrix")
fig.colorbar(im, ax=ax, shrink=0.6)
fig.tight_layout()
fig_path = ASSETS / "multiomics_corr.png"
fig.savefig(fig_path, dpi=150)
plt.close(fig)

# ── Build report ─────────────────────────────────────────────────────────
report = Report(
    title_line1="Multi-Omics Data Integration",
    title_line2="Analysis Report",
    pipeline="MOFA2 · mixOmics · Seurat",
    operator="K. Braun",
    reference="Human multi-omics atlas",
    cluster="Zeus HPC · 512 GB RAM",
    date="2026-06-26",
    run_label="Multi-omics v1.0 · Zeus HPC",
    run_status="Pipeline complete · 96 samples",
    logo_path=Path(__file__).resolve().parents[1] / "Unimed_logo.svg",
    footer_left="Multi-omics pipeline · 2026-06-26",
    footer_right="Generated by the Kaderali Lab · Institute of Bioinformatics, Universitätsmedizin Greifswald",
)
report.set_metadata([
    ("Date", "2026-06-26"),
    ("Samples", "96"),
    ("RNA features", "12,304"),
    ("Proteins", "4,102"),
    ("Metabolites", "842"),
])

summary = report.add_section("01", "Executive Summary", count="96 samples · 3 omics layers")
summary.set_overview(
    "Transcriptomic, proteomic and metabolomic profiles from 96 samples were integrated with MOFA2. "
    "The first two latent factors explained 34% of variance and were associated with disease status."
)
summary.add_metrics([
    {"label": "Samples", "value": "96", "sub": "3 omics layers", "highlight": True},
    {"label": "RNA", "value": "12,304", "sub": "features"},
    {"label": "Proteins", "value": "4,102", "sub": "features"},
    {"label": "Metabolites", "value": "842", "sub": "features"},
    {"label": "Variance (LF1+2)", "value": "34%", "sub": "explained"},
])

omics = report.add_section("02", "Omics Layers", count="QC summary")
omics.add_subsection("Preprocessing", "s2-prep")
omics.add_table(
    headers=["Layer", "Raw features", "Filtered features", "Missing %", "Status"],
    rows=[
        ["Transcriptome", "18,642", "12,304", "2.1", "✓ pass"],
        ["Proteome", "5,801", "4,102", "8.4", "✓ pass"],
        ["Metabolome", "1,204", "842", "4.7", "✓ pass"],
    ],
    caption="Table 1 · Preprocessing summary per omics layer",
    col_classes=[None, "mono", "mono", "mono", None],
    cell_classes=[
        [None, None, None, None, "status pass"],
        [None, None, None, None, "status pass"],
        [None, None, None, None, "status pass"],
    ],
)

integration = report.add_section("03", "Integration", count="MOFA2")
integration.add_subsection("Correlation overview", "s3-corr")
integration.add_figure(fig_path, caption="Pairwise correlation across omics layers and clinical scores.")
integration.add_text(
    "The joint factorisation models each omics view as "
    r"\(\mathbf{X}_m \approx \mathbf{Z} \mathbf{W}_m^\top\), where "
    r"\(\mathbf{Z} \in \mathbb{R}^{N \times K}\) holds the shared latent factors."
)
integration.add_latex(
    r"\mathbf{X}_m = \mathbf{Z} \mathbf{W}_m^\top + \boldsymbol{\epsilon}_m, \quad m = 1, \dots, M",
    display=True,
)
integration.add_subsection("Top loadings", "s3-loadings")
integration.add_table(
    headers=["Factor", "Feature", "Layer", "Loading"],
    rows=[
        ["LF1", "IL6", "Protein", "0.82"],
        ["LF1", "STAT3", "mRNA", "0.76"],
        ["LF1", "kynurenine", "Metabolite", "0.71"],
        ["LF2", "CD8A", "mRNA", "0.68"],
        ["LF2", "C-reactive protein", "Protein", "-0.64"],
    ],
    caption="Table 2 · Highest-loading features per latent factor",
    col_classes=["mono", "mono", None, "mono"],
)

refs = report.add_section("04", "References")
refs.add_references([
    "Argelaguet R. et al. (2020). MOFA+: a statistical framework for comprehensive integration of multi-modal single-cell data. Genome Biology, 21, 111.",
    "Rohart F. et al. (2017). mixOmics: An R package for 'omics feature selection and multiple data integration. PLoS Computational Biology, 13(11), e1005752.",
])

qmd = report.save(OUT, filename="multi_omics_report.qmd")
print(f"Multi-omics report written to: {qmd}")
print("Render with: quarto render", qmd, "--to html")
