"""Example: single-cell RNA-seq quality control and clustering report."""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from bioinformatics_report import Report

OUT = Path(__file__).with_suffix("").parent / "out" / "single_cell"
ASSETS = OUT / "assets"
ASSETS.mkdir(parents=True, exist_ok=True)

# ── Generate placeholder UMAP plot ───────────────────────────────────────
fig, ax = plt.subplots(figsize=(6, 5))
np.random.seed(42)
umap_x = np.random.normal(0, 1, 800)
umap_y = np.random.normal(0, 1, 800)
clusters = np.random.choice(["T-cell", "B-cell", "Monocyte", "NK", "DC"], 800)
for cl in sorted(set(clusters)):
    mask = clusters == cl
    ax.scatter(umap_x[mask], umap_y[mask], label=cl, s=8, alpha=0.7)
ax.set_title("UMAP embedding of single-cell RNA-seq data")
ax.set_xlabel("UMAP-1")
ax.set_ylabel("UMAP-2")
ax.legend(title="Cluster", loc="best", frameon=False)
for spine in ["top", "right"]:
    ax.spines[spine].set_visible(False)
fig.tight_layout()
fig_path = ASSETS / "umap.png"
fig.savefig(fig_path, dpi=150)
plt.close(fig)

# ── Build report ─────────────────────────────────────────────────────────
report = Report(
    title_line1="Single-Cell Transcriptomics",
    title_line2="QC and Clustering Report",
    pipeline="Cell Ranger v8.0 · Scanpy 1.10",
    operator="A. Müller",
    reference="GRCh38-2024-A",
    cluster="Zeus HPC · 128 GB RAM",
    date="2026-06-26",
    run_label="scRNA-seq v8.0 · Zeus HPC",
    run_status="Pipeline complete · 8,412 cells",
    sidebar_footer="Pipeline complete",
    # Swap the logo to any SVG, PNG or JPG; use set_logo() or omit for a placeholder.
    logo_path=Path(__file__).resolve().parent / "assets" / "Unimed_logo.svg",
    footer_left="scRNA-seq pipeline · 2026-06-26",
    footer_right=(
        "Generated by the Kaderali Lab · Institute of Bioinformatics, "
        "Universitätsmedizin Greifswald"
    ),
)
report.set_metadata(
    [
        ("Date", "2026-06-26"),
        ("Samples", "6"),
        ("Cells", "8,412"),
        ("Genes", "18,642"),
        ("Clusters", "5"),
    ]
)

summary = report.add_section("01", "Executive Summary", count="6 samples · 8,412 cells")
summary.set_overview(
    "Single-cell RNA-seq data from six PBMC samples were processed, filtered and clustered. "
    "After quality control, 8,412 cells and 18,642 genes were retained for downstream analysis."
)
summary.add_metrics(
    [
        {"label": "Cells", "value": "8,412", "sub": "after QC", "highlight": True},
        {"label": "Genes", "value": "18,642", "sub": "detected"},
        {"label": "Median Genes", "value": "1,847", "sub": "per cell"},
        {"label": "Clusters", "value": "5", "sub": "Leiden resolution 0.6"},
        {"label": "Doublets", "value": "312", "sub": "removed"},
    ]
)

qc = report.add_section("02", "Quality Control", count="Cell Ranger · Scanpy")
qc.add_subsection("Filtering thresholds", "s2-thresholds")
qc.add_table(
    headers=["Metric", "Min", "Max", "Cells removed"],
    rows=[
        ["nCount_RNA", "500", "25,000", "1,203"],
        ["nFeature_RNA", "200", "7,000", "891"],
        ["percent.mt", "—", "10%", "412"],
        ["percent.rb", "—", "—", "0"],
    ],
    caption="Table 1 · Quality-control thresholds applied to all samples",
    col_classes=["mono", "mono", "mono", "mono"],
)

clustering = report.add_section("03", "Clustering", count="Scanpy · Leiden")
clustering.add_subsection("UMAP", "s3-umap")
clustering.add_figure(fig_path, caption="UMAP embedding coloured by Leiden cluster.")
clustering.add_subsection("Marker genes", "s3-markers")
clustering.add_table(
    headers=["Cluster", "Top marker", "p-value", "Log2FC"],
    rows=[
        ["T-cell", "CD3D", "1.2e-45", "3.41"],
        ["B-cell", "CD79A", "4.5e-38", "2.98"],
        ["Monocyte", "CD14", "2.1e-52", "4.12"],
        ["NK", "NKG7", "8.7e-29", "2.65"],
        ["DC", "FCER1A", "3.3e-21", "2.33"],
    ],
    caption="Table 2 · Top marker genes per cluster",
    col_classes=[None, "mono", "mono", "mono"],
)

refs = report.add_section("04", "References")
refs.add_references(
    [
        "Zheng G. et al. (2017). Massively parallel digital transcriptional "
        "profiling of single cells. Nature Communications, 8, 14049.",
        "Wolf F. et al. (2018). SCANPY: large-scale single-cell gene expression "
        "data analysis. Genome Biology, 19, 15.",
    ]
)

qmd = report.save(OUT, filename="single_cell_report.qmd")
print(f"Single-cell report written to: {qmd}")
print("Render with: quarto render", qmd, "--to html")
