"""Example: spatial transcriptomics report with tissue QC and clustering."""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from bioinformatics_report import Report

OUT = Path(__file__).with_suffix("").parent / "out" / "spatial"
ASSETS = OUT / "assets"
ASSETS.mkdir(parents=True, exist_ok=True)

# ── Generate placeholder spatial plot ────────────────────────────────────
fig, ax = plt.subplots(figsize=(6, 6))
np.random.seed(7)
x = np.random.uniform(0, 100, 1200)
y = np.random.uniform(0, 100, 1200)
clusters = np.random.choice(["Tumor", "Stroma", "Immune", "Normal"], 1200)
colours = {"Tumor": "#264882", "Stroma": "#9FADC4", "Immune": "#D38726", "Normal": "#637A9F"}
for cl in colours:
    mask = clusters == cl
    ax.scatter(x[mask], y[mask], c=colours[cl], label=cl, s=10, alpha=0.7)
ax.set_aspect("equal")
ax.set_title("Spatial transcriptomics clusters")
ax.set_xlabel("x (µm)")
ax.set_ylabel("y (µm)")
ax.legend(title="Region", loc="upper right", frameon=False)
for spine in ["top", "right"]:
    ax.spines[spine].set_visible(False)
fig.tight_layout()
fig_path = ASSETS / "spatial_clusters.png"
fig.savefig(fig_path, dpi=150)
plt.close(fig)

# ── Build report ─────────────────────────────────────────────────────────
report = Report(
    title_line1="Spatial Transcriptomics",
    title_line2="Tissue Analysis Report",
    pipeline="Space Ranger v3.0 · Seurat v5",
    operator="L. Schmidt",
    reference="Visium Human Transcriptome",
    cluster="Zeus HPC · 256 GB RAM",
    date="2026-06-26",
    run_label="Visium v3.0 · Zeus HPC",
    run_status="Pipeline complete · 4 tissue sections",
    sidebar_footer="Pipeline complete",
    # Swap the logo to any SVG, PNG or JPG; use set_logo() or omit for a placeholder.
    logo_path=Path(__file__).resolve().parent / "assets" / "Unimed_logo.svg",
    footer_left="Visium pipeline · 2026-06-26",
    footer_right=(
        "Generated by the Kaderali Lab · Institute of Bioinformatics, "
        "Universitätsmedizin Greifswald"
    ),
)
report.set_metadata(
    [
        ("Date", "2026-06-26"),
        ("Sections", "4"),
        ("Spots", "12,412"),
        ("Genes", "18,085"),
        ("Mean reads/spot", "54,321"),
    ]
)

summary = report.add_section("01", "Executive Summary", count="4 sections · 12,412 spots")
summary.set_overview(
    "Four Visium tissue sections were processed with Space Ranger and analysed "
    "in Seurat. Clustering resolved four major tissue compartments: tumor, "
    "stroma, immune infiltrate and normal epithelium."
)
summary.add_metrics(
    [
        {"label": "Spots", "value": "12,412", "sub": "under tissue", "highlight": True},
        {"label": "Genes", "value": "18,085", "sub": "detected"},
        {"label": "Median UMI", "value": "3,421", "sub": "per spot"},
        {"label": "Clusters", "value": "4", "sub": "spatial domains"},
        {"label": "Tumor spots", "value": "31%", "sub": "of total"},
    ]
)

qc = report.add_section("02", "Spatial QC", count="Space Ranger · Seurat")
qc.add_subsection("Tissue coverage", "s2-coverage")
qc.add_table(
    headers=["Section", "Spots under tissue", "Mean reads", "Mapping %", "Status"],
    rows=[
        ["A1", "3,104", "58,231", "95.4", "✓ pass"],
        ["A2", "3,098", "52,104", "94.1", "✓ pass"],
        ["B1", "3,201", "61,402", "96.0", "✓ pass"],
        ["B2", "3,009", "45,547", "91.8", "✓ pass"],
    ],
    caption="Table 1 · Per-section spatial sequencing metrics",
    col_classes=["mono", "mono", "mono", "mono", None],
    cell_classes=[
        [None, None, None, None, "status pass"],
        [None, None, None, None, "status pass"],
        [None, None, None, None, "status pass"],
        [None, None, None, None, "status pass"],
    ],
)

spatial = report.add_section("03", "Spatial Domains", count="Seurat · SCTransform")
spatial.add_subsection("Cluster map", "s3-clusters")
spatial.add_figure(
    fig_path, caption="Spatial distribution of inferred tissue domains.", width="80%"
)
spatial.add_subsection("Differential expression", "s3-de")
spatial.add_table(
    headers=["Domain", "Top marker", "Avg log2FC", "p-value"],
    rows=[
        ["Tumor", "KRT19", "2.81", "1.4e-62"],
        ["Stroma", "COL1A1", "3.12", "2.8e-55"],
        ["Immune", "PTPRC", "2.45", "7.1e-48"],
        ["Normal", "MUC2", "2.19", "3.3e-33"],
    ],
    caption="Table 2 · Top domain-specific markers",
    col_classes=[None, "mono", "mono", "mono"],
)

refs = report.add_section("04", "References")
refs.add_references(
    [
        "10x Genomics (2024). Space Ranger v3.0. 10x Genomics.",
        "Hao Y. et al. (2024). Dictionary learning for integrative, multimodal "
        "and scalable single-cell analysis. Nature Biotechnology, 42, 293–304.",
    ]
)

qmd = report.save(OUT, filename="spatial_report.qmd")
print(f"Spatial report written to: {qmd}")
print("Render with: quarto render", qmd, "--to html")
